### ISSUE TITLE
Unsafe behaviour on strings with C format control elements—needs documentation

### ISSUE THREAD

**Issue by HiTECNOLOGYs** [HiTECNOLOGYs/cl-charms#6]
This following code crashes SBCL:
```lisp
(cl-charms:initscr)
(cl-charms:printw "%s")
(cl-charms:getch)
(cl-charms:endwin)
```

Possibly has something to do with the way CFFI bindings are defined.

Originally reported by Andrew Lobanov.

**Comment by nathanielchanning** [comment]
I believe this is expected behavior and not a bug. Since 'printw' is a 'printf' style function, it will assume that the c calling convention has been used, and it will look for the appropriate address on the program's stack; However, since an argument hasn't been given to be put on the stack, the value there will be, as far as I know, undefined. This means that what ever value it does find, it will expect to be an address that points to a c string. Given that this address is undefined, there is a possibility that it will try to access an address outside of the program's address space, which would result in a segfault and a crash.

However, there is another problem: since printw is a variadic function, it should be defined as such in low-level bindings. As it stands, trying to run
 ```common-lisp
(with-curses ()
  (charms/ll:printw "%s" "Hello, world.\n")
  (refresh-window *standard-window*)
  (charms/ll:getch))
```
Will result in an error.

**Comment by HiTECNOLOGYs** [comment]
@nathanielchanning if `printw` doesn't do sanity checks, we should. It's inappropriate that such a mistake can lead to crash of the whole program.

**Comment by glider-gun** [comment]
Some might want to use that printf-like features, so it may be reasonable to leave `printw` very low-level (and dangerous), and do escaping #\% character inside high-level functions like `write-string-at-point`.

defining printw as
```common-lisp
(cffi:defcfun "printw" :int
  (fmt :string)
  &rest)
```
makes it variadic, and can be used like
```common-lisp
(progn
  (charms/ll:initscr)
  (charms/ll:clear)
  (charms/ll:printw "%c %d %.2f %s" :char 90 :short 42 :float pi :string "super-locrian")
  (charms:refresh-window (charms:standard-window))
  (charms/ll:getch)
  (charms/ll:end win))
```
(example is taken from https://common-lisp.net/project/cffi/manual/html_node/defcfun.html )

**Comment by tarballs-are-good** [comment]
Maybe we should prepend `unsafe-` to functions which may potentially crash the application if used incorrectly.

**Comment by glider-gun** [comment]
I feel the current simple correspondence of function names, between C and charms/ll, very convenient, so I think it is better to keep it. Noting the risk in docstring won't suffice?

**Comment by tarballs-are-good** [comment]
I think you're probably right.

**Comment by tarballs-are-good** [comment]
I will consider this issue closed when there is documentation of the functions.

**Comment by glider-gun** [comment]
And change of `printw` (and `wprintw`, `mvprintw`, `mvwprintw`(, `vwprintw`, `vw_printw`)) definition for being variadic?
Change in curses-binding.lisp like below seems sufficient.
```common-lisp
(define-exported-cfuns ("printw")
    :int
  (fmt :string))
```
↓
```common-lisp
(define-exported-cfuns ("printw")
    :int
  "print formatted output in curses windows in the same way as C language's printf function.
caution: This function may crash lisp, when format string `fmt` won't match the rest of arguments.

examples:
(printw \"Hello world\")
(printw \"%c %d %.2f %s\" :char 90 :short 42 :float pi :string \"super-locrian\")"
  (fmt :string)
  &rest)
```

**Comment by glider-gun** [comment]
(though perhaps the second example in docstring should be changed, as it is copied from CFFI's documentation page above)

**Comment by glider-gun** [comment]
I made pull request #22 for `printw`-like functions' support for variable arg (with docstring warning its risk).
